export enum COLOURS {
  PRIMARY_SPACE_GREY = "rgba(0,0,0,0.8)",
  SECONDARY_SPACE_GREY = "#424245",
  PRIMARY_WHITE = "#d6d6d6",
  LIGHT_BACKGROUND = "f5f5f7",
}

export const POST_FEED_NUM_LIMIT = 5
